"""Canonical kernel selector metadata names."""

from __future__ import annotations

KERNEL_TYPE_ALIASES = {
    "s": "single layer",
    "single": "single layer",
    "svel": "single layer velocity",
    "svelocity": "single layer velocity",
    "sp": "normal derivative of single layer",
    "sprime": "normal derivative of single layer",
    "st": "tangential derivative of single layer",
    "stau": "tangential derivative of single layer",
    "sg": "gradient of single layer",
    "sgrad": "gradient of single layer",
    "spres": "pressure of single layer",
    "spressure": "pressure of single layer",
    "strac": "traction of single layer",
    "straction": "traction of single layer",
    "shess": "hessian of single layer",
    "hess": "hessian of single layer",
    "lap": "laplacian of single layer",
    "slap": "laplacian of single layer",
    "laplacian": "laplacian of single layer",
    "d": "double layer",
    "double": "double layer",
    "dvel": "double layer velocity",
    "dvelocity": "double layer velocity",
    "dp": "normal derivative of double layer",
    "dprime": "normal derivative of double layer",
    "dg": "gradient of double layer",
    "dgrad": "gradient of double layer",
    "dpres": "pressure of double layer",
    "dpressure": "pressure of double layer",
    "dtrac": "traction of double layer",
    "dtraction": "traction of double layer",
    "dalt": "alternate double layer",
    "daltg": "gradient of alternate double layer",
    "daltgrad": "gradient of alternate double layer",
    "dalttrac": "traction of alternate double layer",
    "dalttraction": "traction of alternate double layer",
    "c": "combined layer",
    "combined": "combined layer",
    "cvel": "combined layer velocity",
    "cvelocity": "combined layer velocity",
    "cp": "normal derivative of combined layer",
    "cprime": "normal derivative of combined layer",
    "cg": "gradient of combined layer",
    "cgrad": "gradient of combined layer",
    "cpres": "pressure of combined layer",
    "cpressure": "pressure of combined layer",
    "ctrac": "traction of combined layer",
    "ctraction": "traction of combined layer",
    "hilb": "hilbert transform",
    "c2tr": "two-trace combined layer",
    "c2trans": "two-trace combined layer",
    "all": "transmission system",
    "trans_sys": "transmission system",
    "ts": "transmission system",
    "trans_rep": "transmission representation",
    "trep": "transmission representation",
    "trans_rep_prime": "normal derivative of transmission representation",
    "trans_rep_p": "normal derivative of transmission representation",
    "trep_p": "normal derivative of transmission representation",
    "trans_rep_grad": "gradient of transmission representation",
    "trans_rep_g": "gradient of transmission representation",
    "trep_g": "gradient of transmission representation",
}


def canonical_kernel_type(kind: str) -> str:
    return KERNEL_TYPE_ALIASES.get(kind.lower(), kind.lower())
