"""Python port of the MATLAB chunkIE package."""

from . import lege
from .chunker import (
    Chunker,
    ChunkerPref,
    chunker,
    chunkerfit,
    chunkerfunc,
    chunkerfuncuni,
    chunkerpoints,
    chunkerpoly,
    chunkerpref,
    merge,
)
from .chunkgraph import ChunkGraph, chunkgraph, chunkgraphinregion, tochunkgraph
from .domain import (
    HypOctNode,
    HypOctTree,
    checkcurveparam,
    ellipse,
    hypoct_uni,
    mergeregions,
    nonflatinterface,
    pointinregion,
    redblue,
    regioninside,
    starfish,
)
from .kernel import Kernel, kernel
from .operators import (
    PointInfo,
    chunkerinterior,
    chunkerintegral,
    chunkerkerneval,
    chunkerkernevalmat,
    chunkermat,
    chunkermatapply,
    pointinfo,
)

__all__ = [
    "Chunker",
    "ChunkerPref",
    "ChunkGraph",
    "Kernel",
    "PointInfo",
    "HypOctNode",
    "HypOctTree",
    "checkcurveparam",
    "chunker",
    "chunkerfit",
    "chunkerfunc",
    "chunkerfuncuni",
    "chunkerpoints",
    "chunkerpoly",
    "chunkgraph",
    "chunkgraphinregion",
    "chunkerinterior",
    "chunkerintegral",
    "chunkerkerneval",
    "chunkerkernevalmat",
    "chunkermat",
    "chunkermatapply",
    "chunkerpref",
    "ellipse",
    "hypoct_uni",
    "kernel",
    "mergeregions",
    "merge",
    "nonflatinterface",
    "lege",
    "pointinregion",
    "pointinfo",
    "redblue",
    "regioninside",
    "starfish",
    "tochunkgraph",
]
