%GENERATE_CHUNKER_OPS_FIXTURE Generate chunker operation parity fixture.

script_dir = fileparts(mfilename('fullpath'));
addpath(script_dir);
[~, outdir] = fixture_context();

cparams_ops = [];
cparams_ops.nchmin = 3;
pref_ops = [];
pref_ops.k = 8;
[chnkr_ops, ab_ops] = chunkerfunc(@fixture_wobbly_curve, cparams_ops, pref_ops);
mat_ops = [1.15, -0.25; 0.35, 0.8];
chnkr_transformed = mat_ops * move(chnkr_ops, [0.35; -0.2], [0.1; 0.2], 0.45, 1.3);

pref_in = [];
pref_in.k = 7;
pref_in.dim = 3;
pref_in.nchmax = 11;
pref_in.nchstor = 4;
pref_in.verttol = 2.0e-9;
pref_out = chunkerpref(pref_in);

storage_pref = [];
storage_pref.k = 4;
storage_pref.dim = 2;
storage_pref.nchmax = 5;
storage_pref.nchstor = 1;
storage = [];
storage.k = storage_pref.k;
storage.dim = storage_pref.dim;
storage.nchmax = storage_pref.nchmax;
storage.nchstor_initial = storage_pref.nchstor;
storage.nchadd = 2;
storage.nchstor_resized = 4;
storage.r_input = reshape((1:(storage.dim*storage.k*storage.nchadd))/10, storage.dim, storage.k, storage.nchadd);
storage.d_input = 1.0 + storage.r_input;
storage.d2_input = -0.25*storage.r_input;
storage.n_input = 2.0 - storage.r_input;
storage.wts_input = reshape((1:(storage.k*storage.nchadd))/20, storage.k, storage.nchadd);
storage.adj_input = [0, 1; 2, 0];
storage_chunker = chunker(storage_pref);
storage_chunker = addchunk(storage_chunker, storage.nchadd);
storage_chunker.r = storage.r_input;
storage_chunker.d = storage.d_input;
storage_chunker.d2 = storage.d2_input;
storage_chunker.n = storage.n_input;
storage_chunker.wts = storage.wts_input;
storage_chunker.adj = storage.adj_input;
storage.checkadjinfo = checkadjinfo(storage_chunker);
storage_chunker = resize(storage_chunker, storage.nchstor_resized);
storage.rstor_resized = storage_chunker.rstor;
storage.dstor_resized = storage_chunker.dstor;
storage.d2stor_resized = storage_chunker.d2stor;
storage.nstor_resized = storage_chunker.nstor;
storage.wtsstor_resized = storage_chunker.wtsstor;
storage.adjstor_resized = storage_chunker.adjstor;
storage_chunker = makedatarows(storage_chunker, 2);
storage.datadim_after_make = storage_chunker.datadim;
storage.data_input = zeros(2, storage.k, storage.nchadd);
storage.data_input(1,:,:) = reshape(1:(storage.k*storage.nchadd), 1, storage.k, storage.nchadd);
storage.data_input(2,:,:) = -storage.data_input(1,:,:);
storage_chunker.data = storage.data_input;
storage_chunker = makedatarows(storage_chunker, 1);
storage.datadim_after_expand = storage_chunker.datadim;
storage.data_after_expand = storage_chunker.data;
storage.datastor_after_expand = storage_chunker.datastor;
storage_chunker = cleardata(storage_chunker);
storage.datadim_after_clear = storage_chunker.datadim;
storage.data_numel_after_clear = numel(storage_chunker.data);

copy_delta = 7.5;
copy_source = chnkr_ops;
copy_mutated = copy_source;
copy_mutated.rstor(1,1,1) = copy_mutated.rstor(1,1,1) + copy_delta;

chunker_ops = [];
chunker_ops.ab = ab_ops;
chunker_ops.mat = mat_ops;
chunker_ops.pref.k = pref_out.k;
chunker_ops.pref.dim = pref_out.dim;
chunker_ops.pref.nchmax = pref_out.nchmax;
chunker_ops.pref.nchstor = pref_out.nchstor;
chunker_ops.pref.verttol = pref_out.verttol;
chunker_ops.storage = storage;
chunker_ops.copy_delta = copy_delta;
chunker_ops.copy_source_first = copy_source.rstor(1,1,1);
chunker_ops.copy_mutated_first = copy_mutated.rstor(1,1,1);
chunker_ops.base = fixture_pack_chunker(chnkr_ops);
chunker_ops.transformed = fixture_pack_chunker(chnkr_transformed);
chunker_ops.diffmat1 = diffmat(chnkr_ops);
chunker_ops.diffmat2 = diffmat(chnkr_ops, 2);
chunker_ops.intmat = intmat(chnkr_ops);
chunker_ops.onesmat = onesmat(chnkr_ops);
chunker_ops.normonesmat = normonesmat(chnkr_ops);
chunker_ops.centroids = centroids(chnkr_ops);

save(fullfile(outdir, 'chunker_ops.mat'), 'chunker_ops');
